### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Deploy On Moonbase Alpha Using Truffle

### ISSUE THREAD

**Issue by albertov19** [dcarpintero/hello-world-by-polkadot#1]
Hi,

Please check the address of the migrations contract. I think you provided the tx hash and no the contract address (its not H160).

Thanks

**Comment by dcarpintero** [comment]
Hi albertov19,

I have redeployed it:
(migration contract address, ERC20 contract address)
0xdDA6327139485221633A1FcD65f4aC932E60A2e1, 0x0d8cc4b8d15D4c3eF1d70af0071376fb26B5669b

Updated submission:
https://github.com/dcarpintero/hello-world-by-polkadot/blob/master/ecosystem/moonalpha-truffle/readme.md
https://github.com/dcarpintero/hello-world-by-polkadot/blob/master/ecosystem/moonalpha-truffle/deployment.png

Many thanks for letting me know
